export enum Structures {
  UNKNOWN = 'unknown',
  OUTPOST = "outpost",
  METAL_MINE = 'metal mine',
  MINERAL_EXTRACTOR = 'mineral extractor',
  FARM = 'farm',
  SOLAR_GENERATOR = 'solar generator',
  CORE_METAL_MINE = 'core metal mine',
  CORE_MINERAL_EXTRACTOR = 'core mineral extractor',
  HYDROPONICS_LAB = 'hydroponics lab',
  SOLAR_ARRAY = 'solar array',
  STRIP_METAL_MINE = 'strip metal mine',
  STRIP_MINERAL_EXTRACTOR = 'strip mineral extractor',
  HYDROPONICS_DOME = 'hydroponics dome',
  SOLAR_STATION = 'solar station',
  JUMP_GATE = 'jump gate',
  HYPERSPACE_BEACON = 'hyperspace beacon',
  SHIP_YARD = 'ship yard',
  LIGHT_WEAPONS_FACTORY = 'light weapons factory',
  HEAVY_WEAPONS_FACTORY = 'heavy weapons factory',
  SPACE_DOCK = 'space dock',
  HOLO_GENERATOR = 'holo generator',
  ARMY_BARRACKS = 'army barracks',
  LEISURE_CENTRE = 'leisure centre',
  MEDICAL_CENTRE = 'medical centre',
  HOSPITAL = 'hospital'
}
